In [3]:
import numpy as np 
import sys

In [11]:
a = np.array([1,2,3],dtype='int16')
print(a)

[1 2 3]


In [4]:
b= np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
#get dimentions
a.ndim

1

In [6]:
b.ndim

2

In [7]:
a.shape

(3,)

In [8]:
b.shape

(2, 3)

In [12]:
#get type
a.dtype

dtype('int16')

In [14]:
#get size show as bytes
a.itemsize

2

In [15]:
# get total size in byte
a.size * a.itemsize

6

In [16]:
a1= np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a1)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [19]:
#get a specifiv elemet [r,c] start from 0
a1[1,5]
a1[1,-2]

13

In [20]:
#get specific row : means all
a1[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [21]:
# get specific colms 
a1[:,2]

array([ 3, 10])

In [22]:
#getting a little more fancy [startindex:endindex:stepsize]
a1[0,1:6:2]

array([2, 4, 6])

In [25]:
#change somethings
a1[1,5] = 20 
print(a1)
a1[:,2] = [1,2]
print(a1)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [30]:
#3-d example
b1= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b1)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [31]:
#get specific element work outside in 
b1[0,1,1]

4

In [33]:
#all 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [34]:
#all 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [37]:
#all 0s matrix
np.zeros((2,3,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [38]:
#all 1s matrix
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [39]:
#any other numer
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [40]:
# Any other number(full_like)
np.full_like(a1.shape,4)

array([4, 4])

In [43]:
# random decimal numbers 
np.random.rand(4,2,3)

array([[[0.30817989, 0.46908429, 0.01551978],
        [0.78542303, 0.64591217, 0.75275288]],

       [[0.71784772, 0.62093201, 0.59979233],
        [0.62753543, 0.13050148, 0.29172203]],

       [[0.68515978, 0.26629578, 0.10968514],
        [0.14633092, 0.72682575, 0.78643324]],

       [[0.03890079, 0.99308006, 0.36162431],
        [0.02489453, 0.22745583, 0.37116729]]])

In [48]:
# random interger values give us from 0 to 7 
np.random.randint(7, size=(3,3))

array([[0, 3, 3],
       [3, 1, 2],
       [0, 3, 5]])

In [49]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [50]:
#
arr= np.array([1,2,3])
r1 = np.repeat(arr,3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [53]:
#two dimentional repeat an array
arr= np.array([[1,2,3]])
r2= np.repeat(arr,3,axis=0)
print(r2)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [58]:
output = np.ones((5,5))
print(output)

z= np.zeros((3,3))
z[1,1] = 9
print(z)

output [1:4,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [64]:
### becareful when copying arrays
c= np.array([1,2,3])
d =c.copy()
#d =c.copy
d[0]=100
print(d)
print(c)

[100   2   3]
[1 2 3]


In [67]:
#mathematics
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [72]:
a+2
a+=2
print(a)

[5 6 7 8]


In [69]:
a*2

array([2, 4, 6, 8])

In [70]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [74]:
b =np.array([1,0,1,0])
print(b)

[1 0 1 0]


In [75]:
#take the sin 
np.sin(a)

array([-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825])

In [77]:
#linear Algebra

a = np.full((2,3),2)
print(a)

[[2 2 2]
 [2 2 2]]


In [80]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)
#can not do thata*b #
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [81]:
c= np.identity(3)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
### statistics
stats= np.array([[1,2,3],[4,5,6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [11]:
np.min(stats ,axis=1)

array([1, 4])

In [7]:
np.max(stats)

6

In [13]:
np.sum(stats,axis=0)

array([5, 7, 9])

In [14]:
np.mean(stats)

3.5

In [16]:
before = np.array([[1,2,3],[4,5,6]])
print(before.shape)

(2, 3)


In [17]:
print(before)

after = before.reshape((6,1))
print(after)

[[1 2 3]
 [4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [19]:
#vertical stacking vectors
v1= np.array([1,2,3,4])
v2=np.array([5,6,7,8])

np.vstack([v1,v2,v2,v1])
np.hstack([v2,v1,v2])

array([5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
#####boolean maskin and advanced indexing 
after > 5

array([[False],
       [False],
       [False],
       [False],
       [False],
       [ True]])

In [ ]:
# you can index with a list in mnumpy
np.array([1,2,3,4,5,6,8,9])